[build]
  publish = "."
  functions = "netlify/functions"

# 使用Netlify Functions代理API请求
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy"
  status = 200
  force = true

# 为所有响应添加CORS头
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept"
    Access-Control-Max-Age = "86400"
